# Generated by Django 5.0.1 on 2024-02-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_beans_and_cream_cafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_grams',
        ),
        migrations.AddField(
            model_name='product',
            name='drink_type',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='gramaj_ml',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='nutritional_values',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price_lei',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
